name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set Debug Environment Variable
      run: echo "DEBUG=false" >> $GITHUB_ENV  # Устанавливаем DEBUG в false для производственной среды
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /var/www/flaskapp
          git pull
          pip install -r requirements.txt
          gunicorn -b localhost:8000 app:app --chdir /var/www/flaskapp
          sudo systemctl restart nginx
          sudo systemctl restart gunicorn
